-- ACCOUNT LEVEL OBJECTS --
USE ROLE ACCOUNTADMIN; 

-- define roles 
SET MY_USER = CURRENT_USER(); 
CREATE OR REPLACE ROLE HOL_ROLE;
GRANT ROLE HOL_ROLE TO ROLE SYSADMIN; 
GRANT ROLE HOL_ROLE TO USER IDENFIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE HOL_ROLE; 
GRANT MONITOR EXECUTAION ON ACCOUNT TO ROLE HOL_ROLE; 
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_ROLE;

-- 
CREATE IF NOT EXISTS DATABASE HOL_DB;
GRANT OWNERSHIP ON DATABASE HOL_DB TO ROLE HOL_ROLE;

-- warehouses 
CREATE OR REPLACE WAREHOUSE HOL_WAREHOUSE WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME = TRUE;
GRANT OWNERSHIP ON WAREHOUSE HOL_WH TO ROLE HOL_ROLE;