-- account level object creation 
USE ROLE ACCOUNTADMIN;
 
-- roles 
SET MY_USER = CURRENT_USER();
CREATE OR REPLCAE ROLE HOL_ROLE; 
GRANT ROLE HOL_ROLW TO ROLE SYSADMIN; 
GRANT ROLE HOL_ROLE TO USER IDENTIFIER($MY_USER);